# Generated by Django 4.0.5 on 2022-06-26 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Nome')),
                ('genre', models.CharField(choices=[('Ação', 'Ação'), ('Aventura', 'Aventura'), ('Cinema de arte', 'Cinema de arte'), ('Chanchada', 'Chanchada'), ('Comédia', 'Comédia'), ('Comédia de ação', 'Comédia de ação'), ('Comédia de terror', 'Comédia de terror'), ('Comédia dramática', 'Comédia dramática'), ('Comédia romântica', 'Comédia romântica'), ('Dança', 'Dança'), ('Documentário', 'Documentário'), ('Docuficção', 'Docuficção'), ('Drama', 'Drama'), ('Espionagem', 'Espionagem'), ('Faroeste', 'Faroeste'), ('Fantasia', 'Fantasia'), ('Fantasia científica', 'Fantasia científica'), ('Ficção científica', 'Ficção científica'), ('Filmes com truques', 'Filmes com truques'), ('Filmes de guerra', 'Filmes de guerra'), ('Mistério', 'Mistério'), ('Musical', 'Musical'), ('Filme policial', 'Filme policial'), ('Romance', 'Romance'), ('Terror', 'Terror'), ('Thriller', 'Thriller')], default='Ação', max_length=35, verbose_name='Gênero')),
                ('duration', models.TimeField(verbose_name='Duração')),
                ('description', models.TextField(max_length=250, verbose_name='Descrição')),
                ('poster', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
