# Generated by Django 4.0.5 on 2022-06-27 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cineflix', '0002_alter_movie_description_alter_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=250, verbose_name='Descrição'),
        ),
    ]
